"""add intro_end and outro_start to analyses

Revision ID: 0cb1637e4e45
Revises: 5afbc2f7ed44
Create Date: 2026-08-27 22:51:37.639093

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0cb1637e4e45'
down_revision: Union[str, Sequence[str], None] = '5afbc2f7ed44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro_end', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('outro_start', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('outro_start')
        batch_op.drop_column('intro_end')

    # ### end Alembic commands ###
