"""cascade deletes and drop redundant pk indexes

Revision ID: 1916d0f45bf3
Revises: 1dfee883412b
Create Date: 2026-08-26 22:29:44.741487

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1916d0f45bf3'
down_revision: Union[str, Sequence[str], None] = '1dfee883412b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_id'))
        batch_op.drop_constraint(batch_op.f('fk_analyses_track_id_tracks'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_analyses_track_id_tracks'), 'tracks', ['track_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_tracks_id'))
        batch_op.drop_constraint(batch_op.f('fk_playlist_tracks_track_id_tracks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_playlist_tracks_playlist_id_playlists'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_playlist_tracks_playlist_id_playlists'), 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_playlist_tracks_track_id_tracks'), 'tracks', ['track_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_id'))
        batch_op.drop_constraint(batch_op.f('fk_playlists_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_playlists_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_id'))
        batch_op.drop_constraint(batch_op.f('fk_tracks_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tracks_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tracks_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tracks_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_tracks_id'), ['id'], unique=False)

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_playlists_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_playlists_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_playlists_id'), ['id'], unique=False)

    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_playlist_tracks_track_id_tracks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_playlist_tracks_playlist_id_playlists'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_playlist_tracks_playlist_id_playlists'), 'playlists', ['playlist_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_playlist_tracks_track_id_tracks'), 'tracks', ['track_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_playlist_tracks_id'), ['id'], unique=False)

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_analyses_track_id_tracks'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_analyses_track_id_tracks'), 'tracks', ['track_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_analyses_id'), ['id'], unique=False)

    # ### end Alembic commands ###
