"""add content_hash to tracks

Revision ID: 42cd00ca544f
Revises: 0cb1637e4e45
Create Date: 2026-08-27 23:37:26.816518

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42cd00ca544f'
down_revision: Union[str, Sequence[str], None] = '0cb1637e4e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tracks_content_hash'), ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_content_hash'))
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
